### ISSUE TITLE
nuke() fails when $CHROOT64/root is a btrfs subvolume

### ISSUE THREAD

**Issue by mylese** [graysky2/clean-chroot-manager#15]
The rm -rf command doesn't work on btrfs subvolumes.

$ sudo ccm c
[yadda yadda]
Generation complete.
$ sudo ccm n
==> Nuking the chroot...
rm: cannot remove ‘/home/myles/tmp/scratch/chroot64/root’: Operation not permitted

Requires this to delete:

btrfs subvolume delete /home/myles/tmp/scratch/chroot64/root

**Comment by graysky2** [comment]
https://github.com/graysky2/clean-chroot-manager/commit/1f024e42bf63337161d89037d3d88712239dc1fb
