### ISSUE TITLE
Adding package to chroot repo... ls: cannot access *.pkg.tar.xz: No such file or directory

### ISSUE THREAD

**Issue by FadeMind** [graysky2/clean-chroot-manager#21]
If custom variable `PKGDEST` is set in makepkg.conf file, then ccm can't find build package after build and cannot add them to installed list in chroot env:

`----> Adding package to chroot repo...`
`ls: cannot access *.pkg.tar.xz: No such file or directory`

**FILES CONFIG**
`clean-chroot-manager.conf` https://pastebin.com/raw.php?i=kkuYpGJC
`makepkg.conf` https://pastebin.com/raw.php?i=eW55rJM7
 
**ISSUE LOG**
https://pastebin.com/raw.php?i=Kif2hrMm

**FILES**

[tomasz@arch linux-firmware-git]$ la
total 28K
drwxr-xr-x  3 tomasz users 4.0K 20.11.2015 16:14 ./
drwxr-xr-x 39 tomasz users 4.0K 14.11.2015 12:56 ../
drwxr-xr-x  7 tomasz users 4.0K 04.11.2015 17:12 linux-firmware-git/
-rw-r--r--  1 tomasz users  519 18.11.2015 22:58 .SRCINFO
-rw-r--r--  1 tomasz users 1.4K 13.11.2015 10:21 PKGBUILD
-rw-r--r--  1 tomasz users  386 20.11.2015 16:13 linux-firmware-git-20151111.1406ec1-1-x86_64-package.log
-rw-r--r--  1 tomasz users   16 20.11.2015 16:13 linux-firmware-git-20151111.1406ec1-1-x86_64-pkgver.log

**BUT if I made package via `makepkg -src` then, makepkg will create an symlink to pkg.tar.xz file in directory, where PKGBUILD is**:

[tomasz@arch linux-firmware-git]$ la
total 28K
drwxr-xr-x  3 tomasz users 4.0K 20.11.2015 16:23 ./
drwxr-xr-x 39 tomasz users 4.0K 14.11.2015 12:56 ../
drwxr-xr-x  7 tomasz users 4.0K 04.11.2015 17:12 linux-firmware-git/
-rw-r--r--  1 tomasz users  519 18.11.2015 22:58 .SRCINFO
-rw-r--r--  1 tomasz users 1.4K 13.11.2015 10:21 PKGBUILD
lrwxrwxrwx  1 tomasz users   74 20.11.2015 16:23 linux-firmware-git-20151111.1406ec1-1-any.pkg.tar.xz -> /var/cache/pacman/aur/linux-firmware-git-20151111.1406ec1-1-any.pkg.tar.xz
[tomasz@arch linux-firmware-git]$

**Comment by graysky2** [comment]
I would have to dig into arch script code to know for sure, but I could be that the chroot cannot access the location you defined for PKGDEST.  Until I can get some time to dig into it, I'll state that modifying PKGDEST is unsupported.

**Comment by mauritiusdadd** [comment]
It is not fault of <i>clean-chroot-manager</i>: in fact, it seems that <i>makechrootpkg</i> does not crate the symlink.

**Comment by graysky2** [comment]
Thanks for the confirmation.  I will close this since modification of deps is out of scope.
