### ISSUE TITLE
[feature request] honor HOST ccache directory for speed up multiple compilations

### ISSUE THREAD

**Issue by FadeMind** [graysky2/clean-chroot-manager#23]
@graysky2 Hi
CCM can honor  HOST ccache and use it in compile?
This cache speed up compilling in some scenarios.
See: https://wiki.archlinux.org/index.php/ccache

**Comment by graysky2** [comment]
I am not an expert but thought that ccache doesn't work in a chroot.  Can you verify that it does?

**Comment by FadeMind** [comment]
You have right. This is not possible.
