### ISSUE TITLE
Alternative to modifying makechrootpkg

### ISSUE THREAD

**Issue by alphaniner** [graysky2/clean-chroot-manager#25]
I think you could avoid the need for makechrootpkg-mod by prepending PACKAGER= and MAKEFLAGS= to calls to unmodified makechrootpkg:

```sh
$ sudo makechrootpkg -c -r '/mnt/build/chroot'
...
$ grep "^PACKAGER\|^MAKEFLAGS" /mnt/build/chroot/alphaniner/etc/makepkg.conf
MAKEFLAGS='-j4'
PACKAGER='alphaniner'
$ sudo PACKAGER='a9' MAKEFLAGS='-j8' makechrootpkg -c -r '/mnt/build/chroot'
...
$ grep "^PACKAGER\|^MAKEFLAGS" /mnt/build/chroot/alphaniner/etc/makepkg.conf
MAKEFLAGS='-j8'
PACKAGER='a9'
```

If the variables are passed empty, makechrootpkg will behave as though they weren't passed:
```sh
$ sudo PACKAGER='' MAKEFLAGS= makechrootpkg -c -r '/mnt/build/chroot'
...
$ grep "^PACKAGER\|^MAKEFLAGS" /mnt/build/chroot/alphaniner/etc/makepkg.conf
MAKEFLAGS='-j4'
PACKAGER='alphaniner'
```

**Comment by graysky2** [comment]
Good idea!

**Comment by alphaniner** [comment]
Forgot to mention, it exporting the variables (within the script) should also work and might be cleaner. That doesn't work when calling makechrootpkg with sudo from the command line so I didn't test it.

**Comment by graysky2** [comment]
Yes, I thought of the export but as you point out, no easy way to pass with sudo so I think your proposal is good.  Certainly more elegant than how I did it.

**Comment by alphaniner** [comment]
Since ccm itself must be run with sudo, exports made within it should work. For example:

test.sh
```sh
#!/bin/bash

export PACKAGER='a9'
export MAKEFLAGS='-j8'

makechrootpkg -c -r $1
```

```sh
$ sudo ./test.sh /mnt/build/chroot
...
$ grep "^PACKAGER\|^MAKEFLAGS" /mnt/build/chroot/alphaniner/etc/makepkg.conf
MAKEFLAGS='-j8'
PACKAGER='a9'
```

**Comment by graysky2** [comment]
I'll just leave it with the defined vars based on the cfg file as such.  Thanks again for pointing it out.
