### ISSUE TITLE
Make it possible to answer the makepkg questions interactively -suggest "i" switch

### ISSUE THREAD

**Issue by Wabuo** [graysky2/clean-chroot-manager#27]
I would love if it would be possible to re enable the interactive answering of the makepkg questions eg. disable the automatic use of the default answers.

For example I want to choose `jre8` and `gcc-multilib` here.

``` sh
resolving dependencies...
:: There are 2 providers available for java-runtime:
:: Repository extra
   1) jre7-openjdk  2) jre8-openjdk

Enter a number (default=1): 
looking for conflicting packages...
:: gcc-multilib and gcc are in conflict. Remove gcc? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: gcc-multilib and gcc are in conflict
==> ERROR: 'pacman' failed to install missing dependencies.
```

I suggest adding an `i` switch to re enable interactive answering.

**Comment by graysky2** [comment]
I need to review how I'm doing this... if this is something that the devtools scripts are doing, I can't modify them to allow for it.  If it's how I am calling the devtools scripts, it might be doable.

**Comment by graysky2** [comment]
It seems possible to allow the selection of 1 or 2 in your case, but the multilib stuff should really be handled by running:
`ccm m` to toggle it on or off

**Comment by Wabuo** [comment]
Nice ...

**Comment by graysky2** [comment]
That doesn't get to your original question.  I have been experimenting a bit based on the --help output of the script but to me it seems as though the default options cannot be overridden and one of them is --noconfirm.  See [this thread](https://bbs.archlinux.org/viewtopic.php?id=209497) I opened but haven't yet received a definitive answer.  I don't have the time to dig into the code of the parent script to verify myself... does it really matter in your use-case (jre7-openjdk vs jre8-openjdk).

**Comment by Wabuo** [comment]
1. It is not importand but I wanted to test somthing.
2. I wanted to save me one clean, I have somthing that needs jre8

**Comment by graysky2** [comment]
Allan emailed me indicating the only way this would be possible is via a modification to the devtools scripts which is out-of-scope of this tool.
