### ISSUE TITLE
Pass -I <pkg> to makechrootpkg

### ISSUE THREAD

**Issue by demizer** [graysky2/clean-chroot-manager#28]
Hello!

I would like clean-chroot-manager to pass -I to makechrootpkg to allow installing a package into the working copy.

A loop will need to be used in argument parsing.

https://github.com/graysky2/clean-chroot-manager/blob/master/common/clean-chroot-manager64.in#L436

Is this a feature that you'd be interested in @graysky2 for clean-chroot-manager? I can do the work.

**Comment by graysky2** [comment]
Is that really needed?  If you build package A in the chroot, it's in the repo.  Now if package B needs A in order to build, assuming that is in the deps or makedeps, it will be installed automatically from the repo.  Is there a use case where that will fail?

**Comment by demizer** [comment]
The problem I ran into that caused me to open this issue was that I was trying to build archzfs against a package that is no longer in the arch repos. In this case kernel 4.5.4 used in the archiso. I can install the package in the root chroot and let makechrootpkg copy that without updating, but that is not as simple as simply passing -I to makechrootpkg.

**Comment by graysky2** [comment]
I am going to close this... a work around is the `a` funtion added a while ago
```
a) Add packages in current dir to the local repo
```
