### ISSUE TITLE
"ERROR: Local repo in chroot is empty. Build something first." after successful build

### ISSUE THREAD

**Issue by cryzed** [graysky2/clean-chroot-manager#30]
Hey, I am attempting to compile [firefox-kde-opensuse](https://aur.archlinux.org/packages/firefox-kde-opensuse/) in a clean chroot, using clean-chroot-manager. To do that I first need to build [kmozillahelper](https://aur.archlinux.org/packages/kmozillahelper/).

After configuring the `clean-chroot-manager.conf` and adjusting the settings everything seems to work perfectly when creating a new chroot using `# ccm c`. `# ccm s` also seems to do the compilation and packaging successfully, however after querying the chroot using `# ccm l` I get the following error message:

`==> ERROR: Local repo in chroot is empty. Build something first.`

The symlink pointing to the package file is also broken: `kmozillahelper-1:0.6.4-1-x86_64.pkg.tar.xz -> /pkgdest/kmozillahelper-1:0.6.4-1-x86_64.pkg.tar.xz` and I can't find any file using

`find $CHROOTPATH64 -name 'kmozillahelper-1:0.6.4-1-x86_64.pkg.tar.xz'`.

My `clean-chroot-manager.conf` looks like this:
```
CHROOTPATH64="/mnt/sdb1/home-data/cryzed/Various/clean-chroot-manager/chroot64"
CHROOTPATH32="/mnt/sdb1/home-data/cryzed/Various/clean-chroot-manager/chroot32"
THREADS=9
PACKAGER=""
CFLAGS="-march=native -O2 -pipe -fstack-protector-strong"
RUNNAMCAP=
RUNDISTCC=
DISTCC_THREADS=
DISTCC_HOSTS="localhost/9 foo/8 bar/4"
```

The last few lines from the build process output:

```
==> Starting package()...
Generating moc_main.cpp
[  0%] Built target kmozillahelper_automoc
Scanning dependencies of target kmozillahelper
[ 33%] Building CXX object CMakeFiles/kmozillahelper.dir/kmozillahelper_automoc.cpp.o
[ 66%] Linking CXX executable kmozillahelper
[100%] Built target kmozillahelper
Install the project...
-- Install configuration: "Release"
-- Installing: /build/kmozillahelper/pkg/kmozillahelper/usr/lib/mozilla/kmozillahelper
-- Installing: /build/kmozillahelper/pkg/kmozillahelper/usr/share/apps/kmozillahelper/kmozillahelper.notifyrc
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "kmozillahelper"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: kmozillahelper 1:0.6.4-1 (Sun Sep 18 16:41:12 CEST 2016)
```

Do you have any idea what I am doing wrong? if I can provide more information please let me know.

**Comment by graysky2** [comment]
I can't reproduce:

```
% cd kmozillahelper
% ccm s
...
<<<builds fine>>>
% ccm l
==> Listing out packages in chroot repo...
-rw-r--r-- 1 root root 22K Sep 18 12:38 kmozillahelper-1:0.6.4-1-x86_64.pkg.tar.xz
```

Are there corresponding log files for your build of kmozillahelper? ie:
```
kmozillahelper-1:0.6.4-1-x86_64-build.log
kmozillahelper-1:0.6.4-1-x86_64-package.log
```

**Comment by cryzed** [comment]
After running `#ccm s`:

```
$ ls -lh
total 24K
-rw-rw-r-- 1 cryzed cryzed  716 Sep 12 22:29 PKGBUILD
-rw-r--r-- 1 cryzed cryzed 8,7K Sep 18 18:55 kmozillahelper-0.6.4.tar.gz
lrwxrwxrwx 1 cryzed cryzed   51 Sep 18 18:56 kmozillahelper-1:0.6.4-1-x86_64.pkg.tar.xz -> /pkgdest/kmozillahelper-1:0.6.4-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 cryzed cryzed 3,3K Sep 18 18:56 kmozillahelper-1:0.6.4-1-x86_64-build.log
-rw-r--r-- 1 cryzed cryzed  536 Sep 18 18:56 kmozillahelper-1:0.6.4-1-x86_64-package.log
```

* [kmozillahelper-1:0.6.4-1-x86_64-build.log](https://gist.github.com/anonymous/71612ba85503e2a4932fe68d0da13add)
* [kmozillahelper-1:0.6.4-1-x86_64-package.log](https://gist.github.com/anonymous/23aca3699c7fc3c5fa73df24c524fcf7)

Additionally `$CHROOTPATH64/cryzed/pkgdest` is empty, however `$CHROOTPATH64/cryzed/build/kmozillahelper/pkg/kmozillahelper` contains the uncompressed package, i.e. the contents of a compiled package file. In this case for example `usr/lib/mozilla/kmozillahelper` etc.

**Comment by graysky2** [comment]
I see... so you have PKGDEST defined in the live `/etc/makepkg.conf`, yes?

**Comment by cryzed** [comment]
Exactly, yes. _Outside_ the chroot, or live, it usually has the following value:

```
$ cat /etc/makepkg.conf | grep PKGDEST
PKGDEST=/mnt/sdb1/makepkg```

Commenting this line out and restarting the whole process fixed the issue.

**Comment by graysky2** [comment]
Yes, arch build scripts work by sourcing the live /etc/makepkg.conf upon invocation.  For key variables in the ccm config to survive, I pass them to the build command [for example](https://github.com/graysky2/clean-chroot-manager/blob/master/common/clean-chroot-manager64.in#L226).  Not sure I know how to handle this one... passing an empty `PKGDEST=` results the the package going to `/pkgdest/foo.pkg.tar.xz` which is wrong.

**Comment by cryzed** [comment]
I think the makepkg behaviour might actually differ between when `PKGDEST` is not set at all (i.e. doesn't exist in the environment) and when it is set but empty. Did you try using `unset` to completely remove it? But I have to admit, I am a bit out of my depth here regarding BASH/Shell-scripting, that's why I usually go with Python or [xonsh](http://xon.sh/) (which is basically Python too).

**Comment by graysky2** [comment]
Yes, I found that to be the case as well.  I will just add a comment in the man page until I or someone things of something to address this issue.  Thanks for reporting.
