### ISSUE TITLE
Use /usr/share/devtools makepkg configs for all archroots

### ISSUE THREAD

**Issue by WorMzy** [graysky2/clean-chroot-manager#31]
I like to build with makepkg options 'strip' and 'debug', as this creates a -debug package alongside the target package (e.g. 'palemoon-26.5.0-1-x86_64.pkg.tar.xz' and 'palemoon-debug-26.5.0-1-x86_64.pkg.tar.xz'), this is easy to accomplish with CCM when building a 32-bit package, as the script uses /usr/share/devtools/makepkg-i686.conf [when making the archroot](https://github.com/graysky2/clean-chroot-manager/blob/master/common/clean-chroot-manager32.in#L145), so you can just edit that file before creating the chroot.

The problem for me is that ccm64 [doesn't use the devtools configs as a source](https://github.com/graysky2/clean-chroot-manager/blob/master/common/clean-chroot-manager64.in#L164), so the default makepkg flags are always used when creating a chroot. Is there a reason for this, or was it just easier to manipulate a freshly installed makepkg.conf on 64-bit chroots?

If the former, would it be possible to add a makepkg flag override to clean-chroot-manager.conf? If the latter, would it be possible to change ccm64 to use the devtools configs as a base?

**Comment by graysky2** [comment]
I have to hit `/usr/share/devtools/{makepkg-i686,pacman-extra}.conf` for 32bit because they're the only i686 confs a pure x86_64 system has.  I could adjust ccm64 but the problem would be that there is not multilib lines in pacman-extra.conf... I'd have it direct it to pacman-multilib.conf and post-process it keeping [multilib] commented.  Perhaps I am missing something?

**Comment by WorMzy** [comment]
I'm not too fussed about the use of the pacman.confs (although it might be worth using one of these for consistency/added flexibility?), it's the makepkg.conf I would like using. So I am proposing this change: https://github.com/WorMzy/clean-chroot-manager/commit/3b01678188b83f69d4e0d30098d9e0429d5408ef

**Comment by Thaodan** [comment]
Using the 64bit templates would be  also better cause when PKGDEST and so on is set on the host system it corrupts the chroot.

**Comment by graysky2** [comment]
@WorMzy - Finally got around to implementing in v2.201... please test.

**Comment by WorMzy** [comment]
Works great, thanks!
