### ISSUE TITLE
per repo settings

### ISSUE THREAD

**Issue by Thaodan** [graysky2/clean-chroot-manager#32]
What abou adding an option that the tool can be runned per repo so that the tool can be runned per config.
Like makepkg with --config option.
This would be especially nice to keep the "local" repo seperated between repos.

**Comment by graysky2** [comment]
PRs are welcomed :)

**Comment by Thaodan** [comment]
Maybe I try tomorrow but today I added another thing: see https://github.com/graysky2/clean-chroot-manager/pull/34

basicly supporting like config would be enough however reffering to the config like git would be a better way.  the next thing on top would be to push the last builded to the repo to publish.

**Comment by Thaodan** [comment]
Currently I manually add each pkg to the git repo of my repo manually  by cp && repo-add

**Comment by graysky2** [comment]
I'm not understanding the per repo aspect... I only plan to keep and manage a single repo within the buildroot.
