### ISSUE TITLE
Adding packages to the local repo

### ISSUE THREAD

**Issue by alejandroliu** [graysky2/clean-chroot-manager#35]
Hi, would it be possible to add an option to add packages to the local repo managed by CCM?

My use case for this is that I use CCM (with other scripts) to keep my own local repo or packages.  I don't really need to keep the chroot forever.  Obviously some packages may depend on others.  But if I nuke the chroot, the next time I need to rebuild one package, I would need to build all its dependancies.

By doing this, I keep the built packages elsewhere, if I need to rebuild one, I create a new chroot, then I just add the dependent packages to the local repo, and start the build of the package I need.

**Comment by graysky2** [comment]
@alejandroliu - Please try f7a4a0f and reopen if it doesn't serve your needs
