### ISSUE TITLE
Relative to compression

### ISSUE THREAD

**Issue by JAClaveroGarcia** [graysky2/clean-chroot-manager#37]
It might be interesting to add the possibility of setting the values ​​for compression in the configuration file clean-chroot-manager.conf. In this way it would be possible to simply default to things such as xz can use multithread. It's just an idea.

**Comment by graysky2** [comment]
This was implemented a with https://github.com/graysky2/clean-chroot-manager/commit/bb35fb349348709c5235caf6aa5f1660f08c178e#diff-13716366207be0b540ca932bc3e9c02e
