### ISSUE TITLE
Can not build packages with conflicting dependencies

### ISSUE THREAD

**Issue by jenrik** [graysky2/clean-chroot-manager#42]
If a packages has a dependency that conflicts with an already installed package the build fails. Pacman offers to replace the already installed package with the dependency but it  automatically receives a no, a solution would be to automatically replace conflicting package without asking

I encountered the problem while building `pam-selinux`, because `pambase-selinux` conflicts `pambase`

**Comment by graysky2** [comment]
PRs are welcomed.

**Comment by jenrik** [comment]
I have been looking for possible solutions. Pacman doesn't have a option for automatically replacing packages that are in conflict with already installed packages, so the only possibly solution I have found yet is to add an options for building a package interactively.
That shouldn't be to hard to implement the primary thing to do is not parsing `--noconfirm` option to pacman
