### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by moparisthebest** [graysky2/clean-chroot-manager#43]
I heavily use clean-chroot-manager for [maintaining](https://github.com/moparisthebest/arch-ppa/blob/master/ppa) a custom shared amd64 pacman repo.  But I'd like to do the same for my raspberry pis, and my pinebook.  These are armv7 and aarch64 respectively, and currently ccm complains like this:

```
[root@pinebook ~]# ccm64 c
==> ERROR: Cannot build 64-bit packages on i686!
```

Have you considered making these usable on other architectures?  I'm thinking it may just involving removing custom architecture detecting code.

**Comment by graysky2** [comment]
I tried porting it out for ARM but found there wasn't a corresponding build option.  The next best thing is to maintain a clean chroot on the device manually (ie an armv6 on armv7) and build it via a `chroot /opt/armv6 /bin/bash` entrance.

**Comment by graysky2** [comment]
@moparisthebest - I came up with a solution I use when building on Arch ARM with a x86_64 distcc volunteer you might like: 
https://github.com/graysky2/distccd-arch-arm
https://github.com/graysky2/bin/blob/master/arm-build
