### ISSUE TITLE
Hardcoded pacman.conf paths break chroot build

### ISSUE THREAD

**Issue by dschaper** [graysky2/clean-chroot-manager#45]
If I use hardcoded paths in the `pacman.conf` file to relocate the metadata for `pacman` I am unable to build a CCH clean root. I have to comment out the `pacman.conf` paths and let them use default.

**Comment by graysky2** [comment]
I haven't considered this use case.  Can you post the relevant examples from your `pacman.conf` here?

**Comment by dschaper** [comment]
It actually will break with the stock directories:

```
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
RootDir     = /
DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
LogFile     = /var/log/pacman.log
GPGDir      = /etc/pacman.d/gnupg/
HookDir     = /etc/pacman.d/hooks/
#HoldPkg     = pacman glibc
```
