### ISSUE TITLE
Recurrent Error Message

### ISSUE THREAD

**Issue by stef204** [graysky2/clean-chroot-manager#51]
I keep getting the following errors when using ccm more than once, so starting with the second time, in same session:

`----> Updating the chroot...
Failed to attach 31191 to compat systemd cgroup /user.slice/user-1000.slice/session-1.scope/payload: No such file or directory
Failed to attach 31165 to compat systemd cgroup /user.slice/user-1000.slice/session-1.scope/supervisor: No such file or directory
Failed to chown() cgroup /sys/fs/cgroup/systemd/user.slice/user-1000.slice/session-1.scope/payload: No such file or directory`

I know this is related to [this](https://lists.archlinux.org/pipermail/arch-dev-public/2018-January/029106.html) thread on the mailing list, but I have not found a definitive solution to eliminate this.

Anything I can do on my side to fix this?

**Comment by graysky2** [comment]
I haven't seen that one before... do you have some custom kernel or customized systemd?

**Comment by stef204** [comment]
I see [this](https://bugs.archlinux.org/task/58892) bug,seems related but why would my system show this error and not another user's with an up-to-date box?

I think you're correct about the adrch-devtools.  I just tried this:

`% arch-nspawn /var/lib/scratch/chroot64/root pacman -Qs pacman 
Failed to attach 6057 to compat systemd cgroup /user.slice/user-1000.slice/session-1.scope/payload: No such file or directory
Failed to attach 6031 to compat systemd cgroup /user.slice/user-1000.slice/session-1.scope/supervisor: No such file or directory
Failed to chown() cgroup /sys/fs/cgroup/systemd/user.slice/user-1000.slice/session-1.scope/payload: No such file or directory
Parent died too early`

with and without sudo privs gives same error.  So it's not your wrapper.

Any idea what could cause this?

**Comment by graysky2** [comment]
I do not... open a FS against devtools.

**Comment by stef204** [comment]
OK, thanks for feedback.

**Comment by graysky2** [comment]
Feel free to reopen if you discover the root cause is ccm but I suspect it's something on your system.
