### ISSUE TITLE
Btrfs support?

### ISSUE THREAD

**Issue by xuanruiqi** [graysky2/clean-chroot-manager#55]
My root FS is Btrfs, and my chroot path is on / (/var/tmp/chroot64). When I attempt to create chroot, I get:

```
==> ERROR: BTRFS targets for building are not supported.
```

According to my understanding, this should have already been fixed in #40. Is this error message indicative of an unimplemented feature, or a bug?

**Comment by graysky2** [comment]
I don't use BTRFS... can you please edit `/usr/bin/ccm` commenting out lines 94-97 and let me know if it works as expected?

**Comment by xuanruiqi** [comment]
It works for me just fine...

**Comment by graysky2** [comment]
@xuanruiqi - How about after multiple calls to build like https://github.com/graysky2/clean-chroot-manager/pull/40#issuecomment-286848205

**Comment by xuanruiqi** [comment]
Let me try.

**Comment by graysky2** [comment]
Thanks, it seems fixed upstream but since I don't have btrfs around I want to get the "OK" from a user who does.

**Comment by xuanruiqi** [comment]
Good, multiple builds also works.

As for the PR, sorry I'm no expert on Btrfs, I just happen to use it. But I think it does work as intended.

**Comment by graysky2** [comment]
Thanks for confirming.  I reopened #40.  I will close this.  Thank you for the interest.
