### ISSUE TITLE
error - Failed to stat /repo: No such file or directory

### ISSUE THREAD

**Issue by stef204** [graysky2/clean-chroot-manager#57]
Starting today, whether I try to update the chroot OR just build a package, it fails with the following error:

`Failed to stat /repo: No such file or directory`

My system is up-to-date.

**Comment by graysky2** [comment]
I just built a package without issue (brand new chroot).  Can you nuke your root and try again?  I did see devtools got an update recently.

**Comment by stef204** [comment]
sure. I was trying to avoid that which is why I posted here first, but I will and report back.

**Comment by stef204** [comment]
All good, nuked and started fresh, issue resolved. I'll close this. Thanks.

**Comment by Adsun701** [comment]
I nuked my chroot and tried again, but the stat error happens again when a package is added for the first time to` /repo`.

**Comment by graysky2** [comment]
I cannot reproduce.  Can you post your `~/.config/clean-chroot-manager.conf`

**Comment by graysky2** [comment]
The problem seems to be that something is modifying the chroot `pacman.conf` to uncomment `CacheDir=` and when ccm runs a 2nd time, a literal `/repo` is getting appended to the default that is uncommented.  I need to dig to see what.

**Comment by stef204** [comment]
I tried to `chattr +i` on the .`$USER/etc/pacman.conf`, to see if it would stay unchanged but doesn't help, rsync throws in a file attribute error and the `/repo` file error still there.
Temporarily downgrading one version of devtools "fixes" issue--but obviously not the solution.
Bug report needed for devtools? Of do you think this is stricty due to ccm?

**Comment by graysky2** [comment]
No, ccm needs to adjust to the new behavior of devtools.  I received an email from Eli Schwartz with some good info and ideas.  I just need some free time to dig into it.

```
It's a lot more likely to have been one of these two commits:
27ff286ee78eb2faac803e3ef67f3171ddfa0098
69112171e5de910331e46cf3f848866550125024

(But most probably the second one, which provided first-class support
for https://bugs.archlinux.org/task/45882 which your script and everyone
else's is probably roughly hacking around.)

I recommend listing your custom repo as
Server = file:///scratch/.chroot/root/repo

Then having that be bind mounted to the same path inside and outside the
chroot.

Although personally I use file:///var/cache/pacman/custom

See also how Anatolik solved the same problem:
https://github.com/anatol/quarry/commit/aa81b86cacb4eaf1cc2d7bcd00b8898c38bb47c7
```

**Comment by anatol** [comment]
devtools changed the way they handle mounted dirs for chroot environment.

there is no `-D` option with `makechrootpkg` option anymore. It takes mounted repos paths from `pacman.conf` itself - all the paths start start with `file://` are now mounted automatically to the *same* path.

In my case the fix was:
 * to remove option `-D` from makechrootpkg
 * use host's path with my custom `Server`
 * I also removed `CacheDir` and it did not affect my functionality.

**Comment by graysky2** [comment]
@anatol - Thank you for the advice.
@stef204 - Please try [v2.97](https://aur.archlinux.org/packages/clean-chroot-manager/) and report back.  Works for me.  Note you need to nuke the chroot first.

**Comment by stef204** [comment]
Looks good to me, works,  Thanks.

**Comment by graysky2** [comment]
From the AUR:
> Hi, I'm also getting that error(Failed to stat /repo: No such file or directory) after building llvm-minimal-git and then trying to build mesa-git with "ccm64 S". This happened with a freshly nuked chroot. Trying to use "ccm64 s" for mesa-git instead gives me the following error "Failed to resolve /home/user/Data/chroot/user//home/user/Data/chroot//root/repo: No such file or directory"

I cannot reproduce.  I built llvm-minimal-git (`ccm s`) and then I built mesa-git (`ccm S`) and both packages built successfully.

**Comment by gillecaluim** [comment]
I'm thinking that maybe there's something different about your system than everyone else's who's having a problem
Perhaps you could create a new arch linux VM and test there?

**Comment by jpapadopoulos** [comment]
I think I figured out what is causing the issue. In my config the path for the chroot was "/path/chroot/" and I noticed in the skel it is "/path/chroot" . Removing the extra slash let me build a second package

**Comment by jpapadopoulos** [comment]
The problem occurs in line 286. When the path is written with a final / it is added to the server path e.g.
"file:///path/to/chroot//root/repo" instead of "file:///path/to/chroot/root/repo" .
Manually removing the slash also fixes the problem for me

**Comment by graysky2** [comment]
@jpapadopoulos - Can you post the output of
`grep CHR ~/.config/clean-chroot-manager.conf`

**Comment by gillecaluim** [comment]
updated to v2.98
after updating tried building jdk8 (which was successful), then tried build mongodb-bin-4.0 ( which failed with the same error)
....
==> Finished making: jdk8 8u202-1 (Thu 17 Oct 2019 01:45:40 PM PDT)
----> Adding all packages in current dir to chroot repo...
==> Adding package '/build/archPKG/custom/chroot64/root/repo/jdk8-8u202-1-x86_64.pkg.tar.xz'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file '/build/archPKG/custom/chroot64/root/repo/chroot_local.db.tar.gz'
[arch@server jdk8]$ cd ../mongodb-bin-4.0
[arch@server mongodb-bin-4.0]$ sudo ccm S
----> Attempting to build package...
Failed to stat /repo: No such file or directory
==> Making package: mongodb-bin-4.0 4.0.12-2 (Thu Oct 17 13:46:38 2019)
==> Retrieving sources...
  -> Found mongodb-org-shell_4.0.12_amd64.deb
  -> Found mongodb-org-server_4.0.12_amd64.deb
  -> Found mongodb-org-mongos_4.0.12_amd64.deb
  -> Found mongodb.service
  -> Found mongodb.conf
  -> Found mongodb.sysusers
  -> Found mongodb.tmpfiles
  -> Found LICENSE
==> Validating source files with sha512sums...
    mongodb-org-shell_4.0.12_amd64.deb ... Passed
    mongodb-org-server_4.0.12_amd64.deb ... Passed
    mongodb-org-mongos_4.0.12_amd64.deb ... Passed
    mongodb.service ... Passed
    mongodb.conf ... Passed
    mongodb.sysusers ... Passed
    mongodb.tmpfiles ... Passed
    LICENSE ... Passed
Failed to stat /repo: No such file or directory
==> ERROR: Build failed, check /build/archPKG/custom/chroot64/arch/build

 grep CHR ~/.config/clean-chroot-manager.conf
CHROOTPATH64="/build/archPKG/custom/chroot64"

**Comment by graysky2** [comment]
Is there anything unique about your setup?  I cannot reproduce this.  What filesystem is on your CHROOTPATH64?

**Comment by gillecaluim** [comment]
the only difference from most is that I've rsync'd the core/extra/community packages unto the server and point to them vs the mirrorlist for pacman and hence building.  I don't run into any issues with makepkg or the extra-x86_64-build methods though
This helps me manage the constant rebuilding/breaking caused by the rolling release of arch linux

**Comment by jpapadopoulos** [comment]
Can you maybe post your chroot's pacman.conf?

**Comment by graysky2** [comment]
@gillecaluim - I think this way me missing the root and user's pacman.conf.  Please try [v2.99](https://github.com/graysky2/clean-chroot-manager/archive/v2.99.tar.gz)/[AUR](https://aur.archlinux.org/packages/clean-chroot-manager/)

**Comment by gillecaluim** [comment]
Success 👍 tried v2.100 and I can build sequential packages with errors 💯 
Thanks for a great package and your perseverance to keeping it great
