### ISSUE TITLE
Toggle multilib command still mentioned in README

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [graysky2/clean-chroot-manager#58]
The "Toggle Multilib" command is still listed in the README when, as far as I could tell at a quick glance, it is no longer available?

If I'm wrong about this I'll sincerely apologize and I must be doing something wrong.

**Comment by graysky2** [comment]
Good catch.

**Comment by severach** [comment]
Why was the multilib toggle removed? I can't build anything multilib until I turn it on manually.

**Comment by graysky2** [comment]
@severach - Dropped when i686 went away.  Consider using defining `CUSTOM_PACMAN_CONF=/usr/share/devtools/pacman-multilib.conf` in your config.
