### ISSUE TITLE
Pacman 5.2 support

### ISSUE THREAD

**Issue by dmp1ce** [graysky2/clean-chroot-manager#59]
MAKEPKG depends on <5.2 but 5.2 was just recently released. Can 5.2 be supported?

https://aur.archlinux.org/packages/clean-chroot-manager/#comment-713046

**Comment by graysky2** [comment]
Yep, it hit [core] faster than I expected!
https://github.com/graysky2/clean-chroot-manager/releases/tag/v2.103
