### ISSUE TITLE
Toggling multilib does not change gcc and such to multilib equivalent

### ISSUE THREAD

**Issue by jasongraham** [graysky2/clean-chroot-manager#6]
Based on the wording you use to describe the multilib toggle, I would expect this to switch the chroot's gcc package to be gcc-multilib and back again.

What are your thoughts about doing this?  Do you intend this to be manual intervention?

**Comment by airvzxf** [comment]
Good solution @shosca ,
I tried this command: `sudo pacman -S --needed --noconfirm gcc-multilib` but always required the user interaction when show the conflicts, right now with your command I solved my personal script [archLinux-installer-and-setup](https://github.com/airvzxf/archLinux-installer-and-setup/blob/master/04-setup/06-video-games.sh)

Solution:
sudo bash -c 'yes | pacman -S --needed gcc-multilib'
