### ISSUE TITLE
Invalid CCACHE_DIR defined 

### ISSUE THREAD

**Issue by fafryd1125** [graysky2/clean-chroot-manager#60]
```bash
$ ccm64 n
==> ERROR: Invalid CCACHE_DIR defined in ~/.config/clean-chroot-manager.conf
```
I don't use CCACHE at all.
tested: v2.202

**Comment by fafryd1125** [comment]
> To build with ccache in the buildroot, uncomment and define the directory where
>  ccache will store its data below.  **If you're using a custom makepkg.conf
>  (see below), you MUST enable ccache that file in addition to defining the path
>  below.** For more info about ccache, see: https://wiki.archlinux.org/index.php/ccache
   
Sorry for the noise. Close

**Comment by graysky2** [comment]
No, you actually found a bug introduced.  If you do not use it and if it is undefined it should pass on.

**Comment by fafryd1125** [comment]
Thank you, works great :smile:
