### ISSUE TITLE
$XDG_CONFIG_HOME not considered

### ISSUE THREAD

**Issue by rpuntaie** [graysky2/clean-chroot-manager#63]
I have `$XDG_CONFIG_HOME` in `~/.local/etc`, but `ccm` creates
`~/.config/clean-chroot-manager.conf`.

**Comment by graysky2** [comment]
Please try this comment and let me know.

**Comment by rpuntaie** [comment]
Yes. Nice.

Maybe also let $CCACE_DIR default to $XDG_CACHE_HOME.

**Comment by graysky2** [comment]
Is $XDG_CACHE_HOME fully implicated by distros?  I believe the default is `$HOME/.cache/` ... I wouldn't want GB of data getting written there myself.

**Comment by rpuntaie** [comment]
ccache is needed, isn't it? Then one should have a default. `$XDG_CACHE_HOME` is meant for caching. https://wiki.archlinux.org/index.php/XDG_Base_Directory.

Something else: I just had `Cannot find the git package needed to handle git sources`.
Could `pkgs` in `create()` take up also additional parameters ($@ after shift), to install packages like git in chroot?

**Comment by graysky2** [comment]
ccache is optional (I think it causes more problems than its worth personally).

Not sure what you're talking about wrt git.  If you're building a git PKGBUILD git should be a makedep.

**Comment by rpuntaie** [comment]
Maybe I misinterpreted the comment in `ccm`.
