### ISSUE TITLE
==> ERROR: Invalid CHROOTPATH64 defined in .config/clean-chroot-manager.conf

### ISSUE THREAD

**Issue by rpuntaie** [graysky2/clean-chroot-manager#65]
If using tmpfs, as you described in the man file, `/scratch/.chroot64` it will be gone after a reboot.

Then `ccm c` returns an error, because the config file is still there.
One needs to remove the config file, which one maybe edited, to re-create the chroot folder via `ccm c`.

I think this should be handled by changing the `fstab` entry to 

```
	tmpfs /scratch/.chroot64 tmpfs nodev,size=20G 0 0
```
Then this would be a doc issue (or just feedback).

**Comment by graysky2** [comment]
https://github.com/graysky2/clean-chroot-manager/blob/master/doc/clean-chroot-manager.1#L85

:D

**Comment by graysky2** [comment]
I think the permissions on that would be `root:root` rather than `youruser:yourgroup` , no?

**Comment by rpuntaie** [comment]
I was referring to the line in your man file:

```
tmpfs /scratch tmpfs nodev,size=20G 0 0
```

I just added the `.chroot64` to avoid the error.

Regarding permission, on my fstab I made it user.
But the permission is not related to the error.
The error is issued based on `[[ ! -d "$CHROOTPATH64" ]]`,
which is true after a boot if you have `/scratch` and not `/scratch/.chroot64` in the fstab.

**Comment by graysky2** [comment]
I agree that without something creating `/scratch/.chroot64/` for you, you will get the error.  My recommendation is to use a `tmpfile.d` entry as shown in the man page:
https://github.com/graysky2/clean-chroot-manager/blob/master/doc/clean-chroot-manager.1#L89-L94

That way, the user you define is the owner and you control the actual permissions (750 or 755 etc.).

**Comment by rpuntaie** [comment]
Oh, I see. `facade` should have become my user name.
I copied without thinking. Thanks.

**Comment by graysky2** [comment]
Maybe I should switch that to foo or something more generic.

**Comment by rpuntaie** [comment]
E.g. `you_user_name_here`.
