### ISSUE TITLE
New Feature: Support custom repo location outside of chroot (picking up from #66) 

### ISSUE THREAD

**Issue by Taijian** [graysky2/clean-chroot-manager#67]
Hi, it's me again!

Picking up from our conversation (mostly me babbling) on issue #66, I have a new patch that I'm using on my system and that seems to work fine, so I thought I'd just pitch it to you again, just to see if you might be interested.

It does two things:

1. Add 2 new variables to $SKEL, allowing users to specify a custom repo location and name
2. Adjust the code in clean-chroot-manager64.in to deal with the new variables and substitute them where appropriate in the code.

I hope this is more workable that the hacky 'solution' I came up with last year!

[ccm.patch.txt](https://github.com/graysky2/clean-chroot-manager/files/6069182/ccm.patch.txt)

**Comment by graysky2** [comment]
Send a PR for review if you want.

**Comment by Taijian** [comment]
OK, PR has been added.

Sorry, took my some days to find the time to actually learn about the github workflow to get here...

**Comment by graysky2** [comment]
OK, continue discussion there, https://github.com/graysky2/clean-chroot-manager/pull/68
