### ISSUE TITLE
nice: error: Unrecognized option: '1'

### ISSUE THREAD

**Issue by Wabuo** [graysky2/clean-chroot-manager#73]
xxx@G6wisejackal ~/D/P/clean-chroot-manager> sudo ccm S
----> Attempting to build package...
nice: error: Unrecognized option: '1'
(yes I'm tying to build ccm in ccm, first PKGBUILD I had flying around)

I keep getting this error no matter what PKGBUILD I try and sadly have no clue how to troubleshoot this one, any tips.

cheers
Wabuo

**Comment by graysky2** [comment]
I cannot reproduce.  What version of coreutils to you have installed?  Post the output of:
```
$ pacman -Qo nice
```
and of
```
$ nice -19 echo "hello"
```

**Comment by graysky2** [comment]
No response for 12 days.  Please reopen if you're still experiencing this.

**Comment by Wabuo** [comment]
Hi
Sorry for the late response, I'm backpacking and literally did not use my laptop for a bit, so forgot about it.

I was using uutils nice ..

Apparently it expects to be called like this `nice -n19 / -n 19 / -n=19[won't work in coreutils]`
I opened an issue over there uutils/coreutils/issues/2251

Looking at `nice --help` it seems like the `-n` should be used any ways, not sure if you want to change it tho. (sorry for this petty shit)
```
Usage: nice [OPTION] [COMMAND [ARG]...]
Run COMMAND with an adjusted niceness, which affects process scheduling.
With no COMMAND, print the current niceness.  Niceness values range from
-20 (most favorable to the process) to 19 (least favorable to the process).

Mandatory arguments to long options are mandatory for short options too.
  -n, --adjustment=N   add integer N to the niceness (default 10)
      --help     display this help and exit
      --version  output version information and exit

NOTE: your shell may have its own version of nice, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/nice>
or available locally via: info '(coreutils) nice invocation'
```
