### ISSUE TITLE
ERROR: Invalid setting for THREADS defined in /usr/share/clean-chroot-manager/ccm.skel

### ISSUE THREAD

**Issue by dreamhunt** [graysky2/clean-chroot-manager#76]
Hello,
I get this error no matter I do. I disabled MAKEFLAGS="-j$(nproc)" in my makepkg.conf and tried to set different THREADS values in ccm.skel to no avail. Any help will be greatly appreciated.

**Comment by graysky2** [comment]
Post the output of:
```
grep THREAD ~/.config/clean-chroot-manager.conf
```

**Comment by dreamhunt** [comment]
The output is empty.

**Comment by graysky2** [comment]
That is a problem.  You should have it defined.  For example:
```
THREADS=9
```

**Comment by dreamhunt** [comment]
Yes I let the system to generate a new .conf and now it's working. Thank you very much!
