### ISSUE TITLE
Why must distcc be installed outside of chroot?

### ISSUE THREAD

**Issue by mipimipi** [graysky2/clean-chroot-manager#78]
Hi,
I've just a (maybe stupid) question. I would like to use distributed builds via distcc in a chroot using clean-chroot-manager. It's clear that the distcc package must be installed in the chroot. But it seems that it also must be installed outside of the chroot. Why is that?
Thanks,
mipi

**Comment by graysky2** [comment]
I believe this is makepkg requirement.  If you try to build without it, `makechrootpkg` will throw an error:
```
==> ERROR: Cannot find the distcc binary required for distributed compilation.
==> ERROR: Could not download sources.
```

**Comment by graysky2** [comment]
Feel free to reopen if I am mistaken.

**Comment by mipimipi** [comment]
@graysky2: Thanks. I investigated that already. makechrootpkg does some consistency checks calling makepkg outside the chroot. This causes the error messages. I thought you know why that is done that way. I might ask the Arch Linux guys.
