### ISSUE TITLE
Using makepkg-x86_64.conf on ARM?

### ISSUE THREAD

**Issue by mipimipi** [graysky2/clean-chroot-manager#79]
Hi,
I saw that you use makefile-x86_64.conf from devtools when the chroot is created. How does that work on ARM? The data in makepkg-x86_64.conf does not fit for that (CARCH="x86_64" or CHOST="x86_64-pc-linux-gnu", for example). That's even the case for devtools-alarm.
Thanks, mipi

**Comment by graysky2** [comment]
What are you wanting to do... use ccm for ARM?  If so, see: https://github.com/graysky2/buildhelper ... if not, explain what you want to achieve so I better understand your question.

**Comment by mipimipi** [comment]
@graysky2: Yes, I want to use it on my Raspi 4. The AUR package does not restrict the architecture. Thus, I thought this should be possible. I will have a look at buildhelper. Thanks.

**Comment by graysky2** [comment]
I build on my RPi4 with [buildhelper](https://github.com/graysky2/buildhelper) which uses a distcc and the Arch ARM toolchain with my x86_64 box doing most of the work.  If you want to build without distcc on the RPi4, you'll need to modify buildhelper to drop it (should be straight forward) if you understand the code.

...I would recommend against that though.  Speed up times are game changing for some projects.  Like building [kodi-rpi-git](https://github.com/archlinuxarm/PKGBUILDs/tree/master/alarm/kodi-rpi-git).  From memory it's done in just 24 minutes with distcc cross-compiling vs 6-7 hours on the RPi4 itself (and it is overclocked to 2.0 GHz).

**Comment by graysky2** [comment]
Anyway, closing this.  If you find buildhelper to be useful or have suggestions, feel free to comment here or open an issue against it.
