### ISSUE TITLE
Locale settings are not being registered

### ISSUE THREAD

**Issue by cmorgenstern** [graysky2/clean-chroot-manager#80]
`clean-chroot-manager-2.222-1`

With the recent update of Perl to 5.36, a number of locale warnings have been cropping up when building packages via `ccm s`. Here is an example of the output from building [lib32-libusb-compat](https://aur.archlinux.org/packages/lib32-libusb-compat):
```
...
==> Extracting sources...
  -> Extracting lib32-libusb-compat-0.1.7.tar.gz with bsdtar
bsdtar: Failed to set default locale
==> Starting prepare()...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
...
```
I nuked and re-created the buildroot, and confirmed that `locale-gen` ran as expected as part of the setup: 
```
...
Generating locales...
  en_US.UTF-8... done
  de_DE.UTF-8... done
Generation complete.
```
However, the locale warnings are still cropping up during builds. I have not customised any of the locale-related files such as `/etc/locale.gen` and `/etc/locale.conf` within the chroot, and the locale generation step on creation appears to have completed successfully.

**Comment by graysky2** [comment]
Have you verified that this issue doesn't also affect devtools alone?

**Comment by cmorgenstern** [comment]
Thanks for the tip - it looks like something is preventing LANG from being persistently set. This is the output when checking the current setting of `LANG` in the chroot:
```
[user@system ~]$ sudo arch-nspawn /home/user/chroot/.chroot64/root printenv | grep LANG
[sudo] password for user: 
LANG=C.UTF-8
```
When I log into the chroot and toggle `LANG` by unsetting it and then sourcing `/etc/profile.d/locale.sh`, it does not persist:
```
[user@system ~]$ sudo arch-nspawn /home/user/chroot/.chroot64/root
[sudo] password for user: 
[root@root ~]# echo $LANG
C.UTF-8
[root@root ~]# unset LANG
[root@root ~]# source /etc/profile.d/locale.sh 
[root@root ~]# echo $LANG
en_US.UTF-8
[root@root ~]# 
logout
[user@system ~]$ sudo arch-nspawn /home/user/chroot/.chroot64/root printenv | grep LANG
[sudo] password for user: 
LANG=C.UTF-8
```
Since [devtools](https://archlinux.org/packages/extra/any/devtools/) has not had an update since March 2022, I wonder if there is something else that is hijacking `LANG` - I'll keep digging. 

I take it you are not experiencing this issue, though?

**Comment by graysky2** [comment]
I have seen it but have not dug into it as it defaults to something sane.  Need to figure out what is to blame, ccm or devtools.

**Comment by graysky2** [comment]
Seems to be happening with devtools on Arch ARM as well (no ccm in the mix):
```
==> Extracting sources...
  -> Extracting xbmc-20.x.60475.fc29968341.tar.gz with bsdtar
bsdtar: Failed to set default locale
  -> Extracting ArchARM-kodi-init-v1.136.tar.gz with bsdtar
bsdtar: Failed to set default locale
...
```

**Comment by graysky2** [comment]
Confirmed, this is not a bug within ccm:
```
% mkdir /scratch/chroot
% CHROOT=/scratch/chroot
% mkarchroot $CHROOT/root base-devel
% cd /scratch/bleachbit-cli
% makechrootpkg -c -r $CHROOT
...
:: Running post-transaction hooks...
(1/1) Warn about old perl modules
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "C.UTF-8"
    are supported and installed on your system.
```

**Comment by cmorgenstern** [comment]
Thanks @graysky2, appreciate you opening a bug in FS - I should have checked there too.
