### ISSUE TITLE
Setting Environment Variables Inside Chroot

### ISSUE THREAD

**Issue by Mushoz** [graysky2/clean-chroot-manager#85]
I am trying to build mesa-git: https://aur.archlinux.org/packages/mesa-git

However, this makepkg file requires you to set a MESA_WHICH_LLVM environment variable to select which LLVM version to build against. Option 1 is recommend, but option 4 is the default. If I use `MESA_WHICH_LLVM=1 ccm s` to build the package, it looks like it's still using the LLVM from the extra repo and ignoring the environment variable. How should I properly set this variable?

**Comment by graysky2** [comment]
In the past, `makechrootpkg` honored flags you would pass but it is not any longer.

Test:
1. Modify the PKGBUILD to simply echo $MESA_WHICH_LLVM (right under the case statement before pkgver's function
2. Run `MESA_WHICH_LLVM=1 makepkg -sd` which for me returns a value of 1
3. Run the same calling `MESA_WHICH_LLVM=1 makechrootpkg -r /scratch/.buildroot -- -A --nocheck` which for me returns a value of 4 which is the PKGBUILD default

Conclusion: makechrootpkg is not honoring the prefixed variable.

One work around is to hardcode your value into the PKGBUILD but that is not very elegant.  You might consider asking in the Arch forums.  This does not appear to be a ccm thing.  It appears to be a `makechrootpkg` thing.

**Comment by LW-archlinux** [comment]
Passing environment variables to an arbitrary porgram is possible **if** its started through sudo .

https://wiki.archlinux.org/title/Sudo#Environment_variables

@graysky2 : maybe you could test to see if  `sudo ccm -E somevar` has effect in your chroot ?

Thanks for a great tool.

**Comment by graysky2** [comment]
Please try it and report back.

**Comment by LW-archlinux** [comment]
I tried but was unable to get things working . 
makechrootpkg does seem use to that method , but is hardcoded to only do it for specific env vars.

**Comment by graysky2** [comment]
I am closing thinking this is not possible.  Not ccm's fault, see above.
