### ISSUE TITLE
Cannot install ccm

### ISSUE THREAD

**Issue by mzryz** [graysky2/clean-chroot-manager#86]
Hi, I am on Manjaro-unstable and I need ccm to install some packages, but I cannot get ccm to install

Typing in sudo pamac build clean-chroot-mananger gets me:

```Warning: cannot resolve "devtools>=1:1.0.0-1", a dependency of "clean-chroot-manager"
Error: Failed to prepare transaction:
could not satisfy dependencies:
- unable to satisfy dependency 'devtools>=1:1.0.0-1' required by clean-chroot-manager
```
I've tried installing devtools-git, devtools, and devtools32-git (all at different times, just to try different versions, through pamac) but each time I get this error trying to install ccm.

If I install devtools-git it says it's installed:
```
Installing devtools-git (1:1.2.0.r1.gd1790c2-1) 
Transaction successfully finished.
```

Could anyone point out what I'm doing wrong? I realise I'm installing a newer version. But the dependency is greater or equal to right? Thank you

**Comment by graysky2** [comment]
No idea about Manjaro.  Works fine on Arch.  Guessing that they are using a different version numbering than Arch is for devtools.  Just edit the `PKGBUILD` and remove the version on the depends of devtools and see if it builds.

**Comment by mzryz** [comment]
@graysky2 Is there any chance you could be a bit more descriptive for me. Sorry for the trouble!  I'm used to building stuff by doing configure / make / install. When downloading the source code for ccm I'm presented with a Makefile. When I type 'make' it tells me 'Setting version' but I don't know what to do.

**Comment by graysky2** [comment]
If you're using Arch or Manjaro (Arch clone) you are doing yourself a huge disservice by compiling without a `PKGBUILD` for the software you want.  See the needed files in the AUR:  https://aur.archlinux.org/packages/clean-chroot-manager

You build with `makepkg` and then install the package you made with `pacman` just like all the official packages.  Makes for a much cleaner and maintainable filesystem.

More to read:
https://wiki.archlinux.org/title/Arch_build_system

**Comment by mzryz** [comment]
Ok I will close the thread, it's all a bit too daunting for me. Hopefully one day ccm can be in the standard repos, so that simple folk like me can install it easily. Thank you for the guidance.

**Comment by graysky2** [comment]
https://aur.archlinux.org/packages/clean-chroot-manager <-- click download snapshot

untar that and cd into the dir

**Comment by mzryz** [comment]
Thank you @graysky2 I now have ccm installed, thanks for your patience.
