### ISSUE TITLE
warning: couldn't find or create package cache, using /tmp/ instead

### ISSUE THREAD

**Issue by Taijian** [graysky2/clean-chroot-manager#88]
Whenever I use ccm to build packages, I get the above warning when it comes time to download the makedeps. This is not an issue per se - the build works fine - but sometimes, when I tinker with patch series, I am rebuilding the same package several times in a row and the makedeps get re-downloaded every time, because they somehow do not get stored in pacman's cache directory.

What am I doing wrong?
-----------------------------------
CHROOTPATH64="/opt/chroot"
THREADS=5
#CUSTOM_PACMAN_CONF='/usr/share/devtools/pacman.conf.d/extra-testing.conf'
#CUSTOM_MAKEPKG_CONF='/usr/share/devtools/makepkg.conf.d/x86_64.conf'
REPO="/var/cache/pacman/aur"
REPO_NAME='local_aur'
#NOCHECK=1
PKGEXT=
PACKAGER="Taijian <taijian@posteo.de>"
RUNNAMCAP=
RUNDISTCC=
DISTCC_THREADS=
#DISTCC_HOSTS="localhost/9 foo/8 bar/4"
CCACHE_DIR="/var/cache/ccache"

**Comment by graysky2** [comment]
That is a pacman message, not anything ccm is generating.  Can you try uncommenting `CUSTOM_MAKEPKG_CONF` the nuke the build root and then create one?

**Comment by Taijian** [comment]
Yeah, that makes the warning go away. Weird...

Thanks, though!

**Comment by graysky2** [comment]
Turns out, this is due to pacman 7.0.0, see commit message in https://github.com/graysky2/clean-chroot-manager/commit/8715a0f7026dd469270a0f736f5a404c39fa625c

Thank you for reporting.

**Comment by Taijian** [comment]
Happy to be of service!
