### ISSUE TITLE
Internal repo not being created

### ISSUE THREAD

**Issue by SJReese** [graysky2/clean-chroot-manager#89]
Greetings:

It appears that the changes in commit 0f5bf8f resulted in the local package repo not being created when using the default internal repo. I'm using ccm to build the ZFS arch packages. The package build process runs normally, but ccm fails when trying to populate the compiled package into /scratch/.biuldroot/root/repo. The error is:

==> Finished making: zfs-utils 2.2.4-1 (Mon Sep 23 08:38:46 2024)
----> Adding all packages in current dir to buildroot repo...
cp: cannot create regular file '/scratch/.buildroot/root/repo': Permission denied

and it happens because /scratch/.buildroot/root/repo doesn't exist, and the copy command is malformed because of that.

I initially tried to fix the issue by moving the code that set/fixed the permissions (lines 145 - 166) out of the trailing slash check to after REPO is set to the defaults. That fixed the immediate problem, but it caused other issues - specifically running 'ccm n' would fail because the REPO folder would be created during check_config and then the root folder would no longer be empty.

In the end, I put the code in create like it was before the change. I included the new permissions setting code there also. That duplicates the code, which isn't great either. Maybe you can come up with a better solution since you know more about how the code should be working.

PR to follow.

**Comment by graysky2** [comment]
@fideliochan - I cannot reproduce.  Post your `~/.config/clean-chroot-manager.conf`

**Comment by graysky2** [comment]
@fideliochan - did you build from git or from v2.229?  I just tagged v2.230 and updated the AUR package.  I suspect it will work as expected.
