### ISSUE TITLE
should I do create new buildroots when I install another packages?

### ISSUE THREAD

**Issue by fideliochan** [graysky2/clean-chroot-manager#91]
Newbie Arch User here, I did not want to use wrappers such as yay, paru etc. so should I create buildroots with ccm u command whenever I install something from AUR?
Thanks.

**Comment by graysky2** [comment]
It's up to you.  I tend to build most things in a buildroot to keep my live system free of needless depends or to make sure the makedeps in the PKGBUILD I am using are correct.  Another use case for buildroots is cross compiling with distcc but that is more niche than the first two for me.

**Comment by graysky2** [comment]
I don't understand your directory question.  You do not need to order them.  If `foo` requires `bar` to build, you just need to build `bar` first and then build `foo`.  The dir tree does not matter.

**Comment by graysky2** [comment]
Yes, or just build bar with ccm then build foo with ccm.  It does it automatically.
