### ISSUE TITLE
error: config file /etc/pacman.d/mirrorlist-debug could not be read: No such file or directory

### ISSUE THREAD

**Issue by LW-archlinux** [graysky2/clean-chroot-manager#92]
clean chroot manager 2.230-1

```
$ sudo ccm u
----> Updating the buildroot...
error: config file /etc/pacman.d/mirrorlist-debug could not be read: No such file or directory
$ 
```

The missing file is present on the host and intended to make installing debug pacakges easier .
It's not really needed at buildtime.

Note:
I had to add .txt extensions to the attached files to convince github to allow them.

[clean-chroot-manager.conf.txt](https://github.com/user-attachments/files/17266493/clean-chroot-manager.conf.txt)
[mirrorlist-debug.txt](https://github.com/user-attachments/files/17266494/mirrorlist-debug.txt)
[pacman.conf.txt](https://github.com/user-attachments/files/17266495/pacman.conf.txt)
[x86_64.conf.txt](https://github.com/user-attachments/files/17266496/x86_64.conf.txt)

**Comment by graysky2** [comment]
clsoing
